### PR TITLE
save create_sampler differently for compatibility with other extensions

### PR DESCRIPTION
**Pull request by szhublox**
saving the original sampler on init() leaves room for other extensions who also overwrite create_sampler to stack on top of your extension

### CODE REVIEW

**Comment by Kahsolt** [comment]
Hi friend @szhublox ~
This PR seems causing some problems, we received broken reports (`RecursionError` due to infinite `create_sampler` recursive call). Though I put a quick fix yesterday, it is still dangerous and somewhat untested. 
We need your further help, what other extensions are you using with that also overwrites `create_sampler()`? Did you test this change really works compatibility with that extension?

Waiting for your response ;)

**Comment by szhublox** [comment]
I don't have a link right now but it's not important enough to keep if it's messing up your extension. I'm surprised it's broken for someone, sorry

**Comment by szhublox** [comment]
To answer your last question, it does fix the other one, so that everyone's create_sampler could call each other in a stack. But maybe there's a better way.

**Comment by pkuliyi2015** [comment]
Please figure out the concrete name or link of your extension. 

As multidiffusion is used by many people and included in many webui variants, it is not responsible to make such a PR without careful test. 

At least you should provide us with the incompatible extension.

**Comment by pkuliyi2015** [comment]
Sorry for the inconvenience. We may rollback the PR.

**Comment by Kahsolt** [comment]
We've rollback this PR for the moment, leave it to consider and verify in the future,
Now anyone effected by this please update to the latest commit eada8e5101417f60850efa15f7454a826da6cf0d

**Pull request merged**
